import { Task } from "./types"

export const mockTasks: Task[] = [
  // EPIC 1: Platform Redesign
  {
    id: "epic-1",
    title: "Platform Redesign Q1",
    description: "Complete redesign of the platform with new branding and UI",
    status: "inProgress",
    priority: "high",
    taskType: "epic",
    parentTaskId: null,
    epicId: null,
    storyId: null,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    estimatedHours: 200,
    assignee: { id: "1", name: "John Doe", avatar: "https://i.pravatar.cc/150?u=1" },
    commentCount: 12,
    attachmentCount: 5,
    projectId: "p1",
    createdAt: "2026-01-01T10:00:00Z",
    updatedAt: "2026-01-04T15:30:00Z",
  },
  // Story under Epic 1
  {
    id: "story-1",
    title: "Design new landing page",
    description: "Create a modern landing page with hero section and feature highlights",
    status: "inProgress",
    priority: "high",
    taskType: "story",
    parentTaskId: "epic-1",
    epicId: "epic-1",
    storyId: null,
    startDate: "2026-01-05",
    dueDate: "2026-01-20",
    estimatedHours: 40,
    assignee: { id: "1", name: "John Doe", avatar: "https://i.pravatar.cc/150?u=1" },
    commentCount: 5,
    attachmentCount: 2,
    projectId: "p1",
    createdAt: "2026-01-01T10:00:00Z",
    updatedAt: "2026-01-04T15:30:00Z",
  },
  // Subtasks under Story 1
  {
    id: "subtask-1",
    title: "Create hero section mockup",
    description: "Design 3 hero section variations",
    status: "complete",
    priority: "high",
    taskType: "subtask",
    parentTaskId: "story-1",
    epicId: "epic-1",
    storyId: "story-1",
    startDate: "2026-01-05",
    dueDate: "2026-01-08",
    estimatedHours: 8,
    assignee: { id: "1", name: "John Doe", avatar: "https://i.pravatar.cc/150?u=1" },
    commentCount: 3,
    attachmentCount: 2,
    projectId: "p1",
    createdAt: "2026-01-01T10:00:00Z",
    updatedAt: "2026-01-04T15:30:00Z",
  },
  {
    id: "subtask-2",
    title: "Implement responsive layout",
    description: "Ensure landing page works on mobile and tablet",
    status: "inProgress",
    priority: "high",
    taskType: "subtask",
    parentTaskId: "story-1",
    epicId: "epic-1",
    storyId: "story-1",
    startDate: "2026-01-09",
    dueDate: "2026-01-15",
    estimatedHours: 12,
    assignee: { id: "2", name: "Jane Smith" },
    commentCount: 2,
    attachmentCount: 0,
    projectId: "p1",
    createdAt: "2026-01-02T09:00:00Z",
    updatedAt: "2026-01-04T14:00:00Z",
  },

  // EPIC 2: Infrastructure Improvements
  {
    id: "epic-2",
    title: "Infrastructure & Performance",
    description: "Improve application performance and infrastructure",
    status: "todo",
    priority: "medium",
    taskType: "epic",
    parentTaskId: null,
    epicId: null,
    storyId: null,
    startDate: "2026-02-01",
    dueDate: "2026-04-30",
    estimatedHours: 150,
    assignee: { id: "3", name: "Bob Johnson" },
    commentCount: 4,
    attachmentCount: 1,
    projectId: "p1",
    createdAt: "2026-01-03T11:00:00Z",
    updatedAt: "2026-01-04T12:00:00Z",
  },
  // Story under Epic 2
  {
    id: "story-2",
    title: "Setup CI/CD pipeline",
    description: "Configure GitHub Actions for automated testing and deployment",
    status: "todo",
    priority: "medium",
    taskType: "story",
    parentTaskId: "epic-2",
    epicId: "epic-2",
    storyId: null,
    startDate: "2026-02-01",
    dueDate: "2026-02-15",
    estimatedHours: 30,
    assignee: { id: "2", name: "Jane Smith" },
    commentCount: 2,
    attachmentCount: 0,
    projectId: "p1",
    createdAt: "2026-01-02T09:00:00Z",
    updatedAt: "2026-01-02T09:00:00Z",
  },
  // Subtasks under Story 2
  {
    id: "subtask-3",
    title: "Configure build pipeline",
    description: "Setup automated builds on push",
    status: "todo",
    priority: "medium",
    taskType: "subtask",
    parentTaskId: "story-2",
    epicId: "epic-2",
    storyId: "story-2",
    startDate: "2026-02-01",
    dueDate: "2026-02-05",
    estimatedHours: 10,
    assignee: { id: "2", name: "Jane Smith" },
    commentCount: 1,
    attachmentCount: 0,
    projectId: "p1",
    createdAt: "2026-01-03T11:00:00Z",
    updatedAt: "2026-01-04T14:00:00Z",
  },

  // Standalone Story (no Epic)
  {
    id: "story-3",
    title: "Fix authentication bug",
    description: "Users are being logged out unexpectedly after 30 minutes",
    status: "overdue",
    priority: "urgent",
    taskType: "story",
    parentTaskId: null,
    epicId: null,
    storyId: null,
    startDate: "2026-01-01",
    dueDate: "2026-01-03",
    estimatedHours: 16,
    assignee: { id: "3", name: "Bob Johnson" },
    commentCount: 8,
    attachmentCount: 1,
    projectId: "p1",
    createdAt: "2026-01-01T14:00:00Z",
    updatedAt: "2026-01-04T12:00:00Z",
  },

  // Story under Epic 1
  {
    id: "story-4",
    title: "Update documentation",
    description: "Add API documentation for new endpoints",
    status: "complete",
    priority: "low",
    taskType: "story",
    parentTaskId: "epic-1",
    epicId: "epic-1",
    storyId: null,
    startDate: "2026-01-10",
    dueDate: "2026-01-25",
    estimatedHours: 20,
    assignee: { id: "1", name: "John Doe", avatar: "https://i.pravatar.cc/150?u=1" },
    commentCount: 1,
    attachmentCount: 3,
    projectId: "p1",
    createdAt: "2026-01-01T08:00:00Z",
    updatedAt: "2026-01-05T10:00:00Z",
  },

  // Story under Epic 1
  {
    id: "story-5",
    title: "Implement dark mode toggle",
    description: "Add theme switcher in user settings",
    status: "inProgress",
    priority: "medium",
    taskType: "story",
    parentTaskId: "epic-1",
    epicId: "epic-1",
    storyId: null,
    startDate: "2026-01-12",
    dueDate: "2026-01-30",
    estimatedHours: 24,
    assignee: { id: "2", name: "Jane Smith" },
    commentCount: 3,
    attachmentCount: 0,
    projectId: "p1",
    createdAt: "2026-01-03T11:00:00Z",
    updatedAt: "2026-01-04T14:00:00Z",
  },
  // Subtask under Story 5
  {
    id: "subtask-4",
    title: "Create theme context",
    description: "Setup React context for theme management",
    status: "complete",
    priority: "medium",
    taskType: "subtask",
    parentTaskId: "story-5",
    epicId: "epic-1",
    storyId: "story-5",
    startDate: "2026-01-12",
    dueDate: "2026-01-15",
    estimatedHours: 6,
    assignee: { id: "2", name: "Jane Smith" },
    commentCount: 1,
    attachmentCount: 0,
    projectId: "p1",
    createdAt: "2026-01-03T11:00:00Z",
    updatedAt: "2026-01-04T14:00:00Z",
  },
]
